### ISSUE TITLE
Feature request: iterate connected components

### ISSUE THREAD

**Issue by vmarkovtsev** [mrapacz/disjoint-set#1]
The current `iter` implementation returns connectivity edges. It would be also useful to be able to iterate over connected components - sets of items which are connected.

**Comment by mrapacz** [comment]
Thanks for the comment! 
Sounds like a useful feature. Just to confirm we're on the same page, here's a sketch of how it could work, let me know should you have any comments.

Let's say the method would be called `itersets()`, it would return an iterator over the sets and then the usage would look as follows:
```python
>>> import disjoint_set
>>> dset = disjoint_set.DisjointSet()
>>> dset.union(1,2)
>>> dset.union(3,4)
>>> list(dset) # <- current __iter__ implementation
[(1, 2), (2, 2), (3, 4), (4, 4)] 
>>> list(dset.itersets()) # <- new method
[{1, 2}, {3, 4}]
```
I can surely add the feature in the following days, but if you also want to take a stab at it, feel free to open any PRs!

**Comment by vmarkovtsev** [comment]
Yep, exactly like this. Thank you for adding this feature :+1:
