### ISSUE TITLE
Improper __get__ method

### ISSUE THREAD

**Issue by ytoku** [mrapacz/disjoint-set#10]
Hello,

The DisjointSet class has `__get__` method, but it does not make sense and the arguments are mismatched.
Is the intended method `__getitem__`?

The improper `__get__` method breaks type cheking:

```python
from disjoint_set import DisjointSet

class Foo:
    _dset: DisjointSet[str]

    def __init__(self) -> None:
        self._dset = DisjointSet()
```

```
$ mypy test.py
test.py:7: error: Too many arguments for "__get__" of "DisjointSet"
test.py:7: error: Argument 1 to "__get__" of "DisjointSet" has incompatible type "Foo"; expected "str"
test.py:7: error: Incompatible types in assignment (expression has type "DisjointSet[<nothing>]", variable has type "str")
Found 3 errors in 1 file (checked 1 source file)
```

**Comment by mrapacz** [comment]
Thanks for reporting this (and sorry for a slight drag in my response). Indeed, this was supposed to be `__getitem__`, not `__get__`. I've just released a patch (`0.7.3`), which should fix this. The example you gave works fine for me now, let me know should it not be the case for you.
