### ISSUE TITLE
Cannot copy a Disjoint Set

### ISSUE THREAD

**Issue by bensherwin0** [mrapacz/disjoint-set#6]
I am running into an error in trying to copy a disjoint set.  If I try to use copy.copy(set), the shallow copies both reference the same data, but copy.deepcopy(set) returns the error "TypeError: __init__() missing 1 required positional argument: 'fun_with_param'".  I get similar errors in trying to use copy.copy(set._data) and set._data.copy().

**Comment by mrapacz** [comment]
Thanks for reporting the issue! Just shipped `0.6.3`, which should fix this. Let me know if the latest version works for you
