### ISSUE TITLE
Future feature annotations not defined

### ISSUE THREAD

**Issue by MatthewZalesak** [mrapacz/disjoint-set#8]
Hi,

I've used pip to install disjoint_set and I'm having trouble importing it because of "future annotations".  I have searched for this error online and the problem seems to be that my organization's system uses Python 3.6 instead of 3.7.  The project says the only requirement is to have Python 3 installed, so I'm not sure if this is a bug that needs to be fixed or if the minimum requirements for this package need to be raised to Python 3.7.  Given that I'm using 3.6, the former would be most helpful.  A copy of the error is included below.  Thanks!

xxx$ pip3 install --user disjoint_set
Collecting disjoint_set
  Downloading https://files.pythonhosted.org/packages/52/43/3f6901a68c78c8fbc392fd9d959e0c51607781574ca1a1fb6444cc5cf4c1/disjoint_set-0.7.0-py3-none-any.whl
Installing collected packages: disjoint-set
Successfully installed disjoint-set-0.7.0
xxx$ python3
Python 3.6.9 (default, Oct  8 2020, 12:12:24)
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import disjoint_set
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/xxx/.local/lib/python3.6/site-packages/disjoint_set/__init__.py", line 1, in <module>
    from .main import DisjointSet
  File "/home/xxx/.local/lib/python3.6/site-packages/disjoint_set/main.py", line 1
    from __future__ import annotations
    ^
SyntaxError: future feature annotations is not defined

**Comment by mrapacz** [comment]
Hi! Thanks for opening the issue. This is true, the latest release of the package broke support for Python 3.6. The current workaround for you would be to use the latest version that worked fine i.e. `0.6.3` - it seems to be working fine for me:
```
$ python --version
Python 3.6.12 :: Anaconda, Inc.

$ pip install disjoint-set==0.6.3
Collecting disjoint-set==0.6.3
  Downloading disjoint_set-0.6.3-py3-none-any.whl (5.5 kB)
Installing collected packages: disjoint-set
Successfully installed disjoint-set-0.6.3

$ python
Python 3.6.12 |Anaconda, Inc.| (default, Sep  8 2020, 17:50:39)
[GCC Clang 10.0.0 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import disjoint_set
>>>
```
I'll fix this and ping you when a patched release is ready.

**Comment by mrapacz** [comment]
@MatthewZalesak just release `0.7.1` and it works fine for me on py36. Let me know should you have any other issues and thanks for reporting this once again! :)
```
$ pip install --upgrade disjoint_set
Collecting disjoint_set
  Downloading disjoint_set-0.7.1-py3-none-any.whl (5.2 kB)
Installing collected packages: disjoint-set
  Attempting uninstall: disjoint-set
    Found existing installation: disjoint-set 0.6.3
    Uninstalling disjoint-set-0.6.3:
      Successfully uninstalled disjoint-set-0.6.3
Successfully installed disjoint-set-0.7.1
$ python
Python 3.6.12 |Anaconda, Inc.| (default, Sep  8 2020, 17:50:39)
[GCC Clang 10.0.0 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import disjoint_set
>>>
