### ISSUE TITLE
Include LICENSE in PyPi tarball

### ISSUE THREAD

**Issue by rpetit3** [mrapacz/disjoint-set#9]
Hello! 

I'm creating a conda-forge install for disjoin-set (https://github.com/conda-forge/staged-recipes/pull/14211). Currently the LICENSE file is not included in the *tar.gz file downloaded from PyPi, so I am manually adding the LICENSE file to the conda recipe.

Would it be possible to include the LICENSE file in the PyPi install?

Thank you very much!
Robert

**Comment by mrapacz** [comment]
Hey @rpetit3, thanks for filing the issue. Sure, I'll aim to publish a new release with the packaged license file by the end of the week. Will ping you once it's done. Hope that works, thanks :)

**Comment by rpetit3** [comment]
Awesome! thank you very much!

**Comment by mrapacz** [comment]
Just pushed `0.7.2` to PyPI with the linecse file included. Gonna close the issue, but feel free to reopen and ping me should you have any concerns :)

**Comment by lbeziaud** [comment]
Hi, version 0.7.3 is missing the LICENSE file in the source tar.gz on PyPi. I guess this is what broke the conda-forge bot at https://github.com/conda-forge/disjoint-set-feedstock/pull/4

**Comment by mrapacz** [comment]
Hey @lbeziaud, thanks for reporting (and sorry for the drag in my response 😓)! I'm not sure why it happened, I published a patched version at `0.7.4` now. The LICENSE file is there in the source files - let me know in case you spot any other issues.
